package com.maxis.db;

public class TransServiceAttributeMap {
	
	private Integer regId;
	private Integer prdRegGroupMapId;
	private String taskId;
	private String headerName;
	private String isMandatory;
	private String autoGenerated;
	private String isEditable;
	private String regex;
	private String isHidden;
	private String forView;
	private Integer mapId;
	public Integer getMapId() {
		return mapId;
	}
	public void setMapId(Integer mapId) {
		this.mapId = mapId;
	}
	public Integer getRegId() {
		return regId;
	}
	public void setRegId(Integer regId) {
		this.regId = regId;
	}
	public Integer getPrdRegGroupMapId() {
		return prdRegGroupMapId;
	}
	public void setPrdRegGroupMapId(Integer prdRegGroupMapId) {
		this.prdRegGroupMapId = prdRegGroupMapId;
	}
	public String getTaskId() {
		return taskId;
	}
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}
	public String getHeaderName() {
		return headerName;
	}
	public void setHeaderName(String headerName) {
		this.headerName = headerName;
	}
	public String getIsMandatory() {
		return isMandatory;
	}
	public void setIsMandatory(String isMandatory) {
		this.isMandatory = isMandatory;
	}
	public String getAutoGenerated() {
		return autoGenerated;
	}
	public void setAutoGenerated(String autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
	public String getIsEditable() {
		return isEditable;
	}
	public void setIsEditable(String isEditable) {
		this.isEditable = isEditable;
	}
	public String getRegex() {
		return regex;
	}
	public void setRegex(String regex) {
		this.regex = regex;
	}
	public String getForView() {
		return forView;
	}
	public void setForView(String forView) {
		this.forView = forView;
	}
	public String getIsHidden() {
		return isHidden;
	}
	public void setIsHidden(String isHidden) {
		this.isHidden = isHidden;
	}
}
